[2025-09-09T16:58:51.316652] [INFO] [SYSTEM] Start new run (run_id=da809875-79d8-4a68-8aad-28c061ed7b2c)
[2025-09-09T16:59:17.288048] [INFO] [GENERAL] debug_utils.py:log_debug:228 - User int input valid: 0
[2025-09-09T16:59:17.289418] [INFO] [CRYPTO] debug_utils.py:log_debug:228 - Counts computed for kit build.
[2025-09-09T16:59:21.135319] [ERROR] [GENERAL] debug_utils.py:log_exception:276 - Error during encrypted kit preparation
